// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0lJ6Mr6YzJY_o9vbsaDBXN5koIQLDUUY',
    appId: '1:729150704195:web:6168aa2b41d58fd5ea62f6',
    messagingSenderId: '729150704195',
    projectId: 'mehd-ai',
    authDomain: 'mehd-ai.firebaseapp.com',
    storageBucket: 'mehd-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS9Kf62V2AQu79AOdNLOIEG7ZZwWiO6rM',
    appId: '1:729150704195:android:ff5acfce566358e9ea62f6',
    messagingSenderId: '729150704195',
    projectId: 'mehd-ai',
    storageBucket: 'mehd-ai.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0lJ6Mr6YzJY_o9vbsaDBXN5koIQLDUUY',
    appId: '1:729150704195:web:433a0c3ed6b1e33cea62f6',
    messagingSenderId: '729150704195',
    projectId: 'mehd-ai',
    authDomain: 'mehd-ai.firebaseapp.com',
    storageBucket: 'mehd-ai.firebasestorage.app',
  );
}
